### ISSUE TITLE
Package with . not supported (intro.js)

### ISSUE THREAD

**Issue by timsun28** [JorgenVatle/meteor-vite#208]
Hi,

I'm having an issue where with the latest meteor-vite 1.11.0 I can't get into my dev environment because a package contains a dot in the name and this isn't supported by mongo.

I've pasted the error logs below. 
```
Vite: Failed to send IPC event! Error [MinimongoError]: Key intro.js must not contain '.'
at MinimongoError (packages/minimongo/common.js:1085:17)
at assertIsValidFieldName (packages/minimongo/local_collection.js:2316:11)
at Object.<anonymous> (packages/minimongo/local_collection.js:2307:7)
at JSON.stringify (<anonymous>)
at assertHasValidFieldNames (packages/minimongo/local_collection.js:2306:10)
at LocalCollection.prepareInsert (packages/minimongo/local_collection.js:108:5)
at LocalCollection.insertAsync (packages/minimongo/local_collection.js:175:21)
at Collection._insertAsync (packages/mongo/collection.js:826:29)
at Collection.insertAsync (packages/mongo/collection.js:839:17)
at DDP_IPC.call (packages/jorgenvatle:vite-bundler/api/DDP-IPC.ts:28:23)
at Object.call (packages/jorgenvatle:vite-bundler/workers.ts:90:29)
at module.wrapAsync.self (packages/jorgenvatle:vite-bundler/vite-server.ts:42:16)
at Module.wrapAsync (/Users/timo.frionnet/.meteor/packages/modules/.0.20.2.1q784fv.yqt3k++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/@meteorjs/reify/lib/runtime/index.js:252:8)
at module (/Users/timo.frionnet/Github-projects/vite-files-bug/.meteor/local/build/programs/server/packages/jorgenvatle_vite-bundler.js:26:9)
at fileEvaluate (packages/modules-runtime.js:335:7)
at Module.require (packages/modules-runtime.js:237:14)
```

For a reproduction you can run meteor npm run start with [this project](https://github.com/timsun28/reproduction-vite-server-reload/tree/bug-dot-package)

From what I found [online](https://stackoverflow.com/questions/12397118/mongodb-dot-in-key-name) a dot is not supported in the keys of mongodb. A possible solution would be to pick a different schema or use something like a hash or replacement for the dot.

I tried to find the cause of this issue, but I couldn't really find where this was being inserted. Let me know if I can help in any other way.

**Comment by JorgenVatle** [comment]
Thanks for the heads up. Got some patch releases going up now that should address the issue.

`meteor-vite@1.11.1` and `jorgenvatle:vite-bundler@2.1.3` should resolve the issue for you.

**Comment by timsun28** [comment]
This fixed the issue I was having, thank you!
