### ISSUE TITLE
Removal of existing Meteor build plugins?

### ISSUE THREAD

**Issue by timsun28** [JorgenVatle/meteor-vite#268]
While I was going through the readme.md I came across this line:

https://github.com/JorgenVatle/meteor-vite/blob/006c605fd64d91a81569b9f8b6028bf5654294d5/README.md?plain=1#L130

Could you clarify this if this is the typescript package from meteor or from npm and what other build plugins we can remove from our project? 

Looking at the [example react project](https://github.com/JorgenVatle/meteor-vite/blob/release/examples/react/.meteor/packages) which packages could be removed from this project?

**Comment by JorgenVatle** [comment]
Oh thanks for the heads up. I'll be sure to update the docs to clarify.

It refers to packages added through Atmosphere. Legacy plugins like `fourseven:scss` and `akryum:vue-component` are all superseded by Vite and can be removed from your Meteor dependencies. Essentially any Meteor package that tries to compile something for your app. Those types of Meteor plugins don't seem to be very common anymore, so for most users, I think `typescript` is probably the only package that applies.

So for the React example project, there isn't really anything to remove. In your npm dependencies you would still want to keep the `typescript` package.

If you have a Meteor package that adds TSX support or something like that you can remove it and just add a Vite plugin instead. There shouldn't be any conflicts if any packages remain in your Meteor project. Just something that can save a few seconds of build time if they are removed.

**Comment by timsun28** [comment]
Thank you for clarifying,

I had a look at my React project Atmosphere package file and would just like to get your feedback on this and possibly help extend the documentation for others, seeing how most of these are quite popular.

[Hot-module-replacement](https://atmospherejs.com/meteor/hot-module-replacement)
[Standard-minifier-css](https://atmospherejs.com/meteor/standard-minifier-css)
[Standard-minifier-js](https://atmospherejs.com/meteor/standard-minifier-js)
[Static-html](https://atmospherejs.com/meteor/static-html)

Update: After trying to remove the typescript atmosphere package i got the following errors when running the project: 
```
=> Errors prevented startup:                  
   
   While building the application:
   error: Could not find mainModule for 'os' architecture: server/main.ts
   Check the "meteor" section of your package.json file?
   error: Could not find mainModule for 'web.browser' architecture: client/main.tsx
   Check the "meteor" section of your package.json file?
   error: Could not find mainModule for 'web.browser.legacy' architecture: client/main.tsx
   Check the "meteor" section of your package.json file?
```

This can be reproduced in my demo app on the vite-bundler branch: 
https://github.com/timsun28/tanstack-query-todo/tree/vite-bundler

**Comment by JorgenVatle** [comment]
Alright, I see there's a few caveats. `static-html` is necessary to serve static HTML and JS/CSS to clients. Without it, Meteor won't serve anything but DDP requests unless I'm mistaken. I think that could cause some errors similar to those errors there. Probably should've been listed in `jorgenvatle:vite`'s dependencies  to be fair. 😄

While not necessary, the only compiler package one would want to keep is `standard-minifier-js` as it bundles your Meteor packages into a single module for the browser. Meteor's packaging system is a bit different to how npm generally is used wherein instead of building packages before publishing, Meteor will instead use the depending app's build configuration to build its dependencies as needed. Meteor-Vite currently only builds source files for your application,

`standard-minifier-css` and `hot-module-replacement` should be completely safe to omit.

For those errors specifically, just rename your `mainModule` files to have a '.js' extension. The modules referenced in `package.json` will only be read by Meteor. Whereas those defined in your Vite config will be handled by Vite's build system and then fed into Meteor as plain JS/CSS.

**Comment by JorgenVatle** [comment]
Looking at the project listed, `typescript` is still necessary as only the client is being built with Vite. Enabling the `serverEntry` in your Vite config should resolve that though. Make sure Meteor is pointed to a plain `.js` file.

So, just add a new `main.js` file to your server directory. Then update the server mainModule in your `package.json` to point to the `server/main.js` file. Finally update your Vite config to point include a `serverEntry` field pointing to `server/main.ts`.

**Comment by timsun28** [comment]
Thank you for clarifying! 

I had a look at the [pull request](https://github.com/timsun28/tanstack-query-todo/pull/5) you had created to fix these issue, but I'm now running into different problems regarding zodern-relay. 

I found that this issue has to do with the todo.ts method file where it ```import { createMethod } from "meteor/zodern:relay";```

This might be because i have zodern:relay as a local package here, but before I look further into this, could you tell me if you have the same issue or if I'm doing something wrong here? 

Error logs:

```
 ⚡  [DEV] Loading server entry: /Users/timo.frionnet/Github-projects/tanstack-query-todo/server/main.ts
 error on boot.js 
 
 ______[MeteorPackageError]___________________________________________________________
 ⚡   <zodern:relay/client>: 
  ERROR  Could not locate module for path: /client! (server)
 undefined
 
 --[Error Stack]----------------------------------------------------------------------
     at _MeteorPackage.getModule (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/meteor/package/components/MeteorPackage.ts:105:19)
     at stubTemplate (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/meteor/package/StubTemplate.ts:24:37)
     at LoadPluginContext.load (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/MeteorStubs.ts:54:30)
     at EnvironmentPluginContainer.load (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:46973:22)
     at loadAndTransform (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40786:22)
 
  🐛  Report an issue:
   -  https://github.com/JorgenVatle/meteor-vite/issues
 _____________________________________________________________________________________
  {
   meteorPackage: _MeteorPackage {
     name: 'zodern:relay',
     modules: { 'server-main.ts': [Array], 'pipeline-helpers.ts': [Array] },
     mainModulePath: '/node_modules/meteor/zodern:relay/server-main.ts',
     lazyMainModulePath: 'server-main.ts',
     packageScopeExports: [],
     packageId: 'meteor/zodern:relay',
     parsedPackage: {
       name: 'zodern:relay',
       modules: [Object],
       packageScopeExports: [Object],
       mainModulePath: '/node_modules/meteor/zodern:relay/server-main.ts',
       packageId: 'meteor/zodern:relay',
       node_modules: [],
       type: 'atmosphere',
       packageJson: undefined
     },
     meta: {
       timeSpent: '3ms',
       ignoreDuplicateExportsInPackages: undefined,
       viteEnv: 'server',
       lazyMainModulePath: 'server-main.ts'
     }
   },
   runnerError: Error: RunnerError
       at reviveInvokeError (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:545:18)
       at Object.invoke (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:628:15)
       at ModuleRunner.getModuleInformation (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1200:73)
       at request (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1222:88)
       at eval (/Users/timo.frionnet/Github-projects/tanstack-query-todo/imports/methods/todo.ts:3:44)
       at ESModulesEvaluator.runInlinedModule (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1053:5)
       at ModuleRunner.directRequest (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1279:61)
       at ModuleRunner.cachedRequest (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1174:76)
       at eval (/Users/timo.frionnet/Github-projects/tanstack-query-todo/server/main.ts:6:31)
       at ESModulesEvaluator.runInlinedModule (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1053:5)
       at ModuleRunner.directRequest (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1279:61)
       at ModuleRunner.cachedRequest (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1174:76)
       at ModuleRunner.import (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/module-runner.js:1111:12)
       at file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/dist/DevelopmentEnvironment-5C6564EF.mjs:37:5
       at /tools/static-assets/server/boot.js:453:5
       at /tools/static-assets/server/boot.js:504:7
       at startServerProcess (/tools/static-assets/server/boot.js:501:3)
 }
 
 
 ______[MeteorPackageError]___________________________________________________________
 ⚡   <zodern:relay/client>: 
  ERROR  Could not locate module for path: /client! (server)
 undefined
 
 --[Error Stack]----------------------------------------------------------------------
     at _MeteorPackage.getModule (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/meteor/package/components/MeteorPackage.ts:105:19)
     at stubTemplate (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/meteor/package/StubTemplate.ts:24:37)
     at LoadPluginContext.load (/Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/meteor-vite/src/entry/plugin/MeteorStubs.ts:54:30)
     at EnvironmentPluginContainer.load (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:46973:22)
     at loadAndTransform (file:///Users/timo.frionnet/Github-projects/tanstack-query-todo/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40786:22)
 
  🐛  Report an issue:
   -  https://github.com/JorgenVatle/meteor-vite/issues
 _____________________________________________________________________________________
 
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by JorgenVatle** [comment]
Oh, in the pull request I lazily removed the `zodern:relay` import from your Meteor client mainModule thinking it would be added back automatically the next time the app is started.

I'll check in a bit to verify. But adding `import 'meteor/zodern:relay/client'` to back into your client mainModule should resolve the issue.

**Comment by timsun28** [comment]
When running the code again, it automatically added back this import, so that doesn't really fix it. 

I also tried renaming the vite server entrypoint, seeing I thought this could lead to possible conflicts it being main.js and main.ts. But this didn't really help resolve anything aswell. You can view my working branch pull request here: https://github.com/timsun28/tanstack-query-todo/pull/6

**Comment by JorgenVatle** [comment]
Alright, yeah, doesn't work on my end either. Thanks for the reference branch there. I'll try to get the issue dealt with over the weekend. 👍

**Comment by JorgenVatle** [comment]
Actually, seems like just updating Vite plugin for `zodern:relay` should did the trick. Not entirely sure how that would be related to the error emitted, but works for me. I'll still be available over the weekend though if it wasn't just a fluke. 😂

![image](https://github.com/user-attachments/assets/787e1674-b903-4f0e-afde-d4a1db1c7e36)

**Comment by timsun28** [comment]
Works for me as well! I've merged the branch so all is good on [vite-bundler](https://github.com/timsun28/tanstack-query-todo/tree/vite-bundler) branch.

Thank you!
