### ISSUE TITLE
Error: Could not find Vite manifest in Meteor client program manifest

### ISSUE THREAD

**Issue by diavrank** [JorgenVatle/meteor-vite#269]
Hi, I am using the Disney's `meteor-base` docker [image](https://github.com/disney/meteor-base) and the build process worked with no errors. However, when I start the container, I get this error:

`````shell
Node.js v20.18.0
app                    | Connecting to MongoDB...
app                    | (node:7) [MONGODB DRIVER] Warning: Warning: no saslprep library specified. Passwords will not be sanitized
app                    | (Use `node --trace-warnings ...` to show where the warning was created)
app                    | Successfully connected to MongoDB
app                    | Starting app...
app                    | packages/core-runtime.js:189
app                    |             throw error;
app                    |             ^
app                    | 
app                    | Error: Could not find Vite manifest in Meteor client program manifest
app                    |     at ViteProductionBoilerplate.get viteManifest [as viteManifest] (packages/jorgenvatle:vite-bundler/src/vite-boilerplate/production.ts:132:19)
app                    |     at ViteProductionBoilerplate.get assetDir [as assetDir] (packages/jorgenvatle:vite-bundler/src/vite-boilerplate/production.ts:17:27)
app                    |     at module.wrapAsync.self (packages/jorgenvatle:vite-bundler/src/server.ts:37:39)
app                    |     at Module.wrapAsync (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:252:8)
app                    |     at module (/opt/bundle/bundle/programs/server/packages/jorgenvatle_vite-bundler.js:26:9)
app                    |     at fileEvaluate (packages/modules-runtime.js:335:7)
app                    |     at Module.require (packages/modules-runtime.js:237:14)
app                    |     at Module.mod.require (/opt/bundle/bundle/programs/server/npm/node_modules/meteor/modules/node_modules/@meteorjs/reify/lib/runtime/index.js:30:33)
app                    |     at Object.require (packages/modules-runtime.js:257:21)
app                    |     at evaluateNextModule (packages/core-runtime.js:167:26)
app                    |     at runEagerModules (packages/core-runtime.js:206:3)
app                    |     at processNext (packages/core-runtime.js:128:3)
app                    |     at packages/core-runtime.js:138:5
app                    |     at evaluateNextModule (packages/core-runtime.js:163:14)
app                    |     at evaluateNextModule (packages/core-runtime.js:202:7)
app                    |     at evaluateNextModule (packages/core-runtime.js:202:7)
`````

**Info:**

- Meteor 3.0.4
- Vue 3.2
- jorgenvatle:vite-bundler@3.0.0
- "vite": "^4.0.5",
- "meteor-vite": "1.10.4",
- [Meteor 2](https://github.com/JorgenVatle/meteor-vite?tab=readme-ov-file#meteor-v2) configutation

Should I use [Meteor 3](https://github.com/JorgenVatle/meteor-vite?tab=readme-ov-file#meteor-v3) configuration?

**Comment by diavrank** [comment]
I used the Meteor 3 configuration and Vite 6, so the issue has gone https://github.com/JorgenVatle/meteor-vite/issues/246#issuecomment-2533310997
