### ISSUE TITLE
build for mobile error

### ISSUE THREAD

**Issue by harry-73** [JorgenVatle/meteor-vite#53]
Hi,

I have this issue when trying to build:

```
⚡️ Building packages to make them available to export analyzer...
Errors prevented bundling:                    
While loading plugin `vite` from package `jorgenvatle:vite-bundler`:
<runJavaScript-40>:927:11: Command failed with exit code 1: meteor build /tmp/meteor-vite/inventory/bundle/meteor --directory
Supply the server hostname and port in the --server option for mobile app
builds.


Changes to your project's package version selections:

minifier-css           removed from your project
minifier-js            removed from your project
standard-minifier-css  removed from your project
standard-minifier-js   removed from your project

at makeError (<runJavaScript-40>:927:11)
at execaSync (<runJavaScript-40>:783:17)
at packages/vite/build.js:108:3
at module (packages/vite/build.js:247:2)
at fileEvaluate (packages/modules-runtime.js:336:7)
at Module.require (packages/modules-runtime.js:238:14)
at require (packages/modules-runtime.js:258:21)
at <runJavaScript-40>:2284:1
at <runJavaScript-40>:2290:3
```

**Comment by JorgenVatle** [comment]
Oh, I'll see if I can't get a hotfix out for you shortly. 👍

**Comment by JorgenVatle** [comment]
This should be fixed with [`jorgenvatle:vite-bundler@v1.6.1`](https://atmospherejs.com/jorgenvatle/vite-bundler). Let me know how it goes! 🤞

**Comment by harry-73** [comment]
It works. Thanks.

**Comment by JorgenVatle** [comment]
Perfect! Thanks for confirming. 🙌
